version: '3.8'
services:
  node-app:
    build:
      context: .
      target: devlopment
    volumes:
      - ./src:/app/src:ro
    environment:
      - NODE_ENV=devlopment
    command: npm run start-dev