
services:
  node-app:
    image: a7medsayed/express-node-app
    env_file:
      - ./.env
    depends_on:
      - mongo 
      - redis 

  # postgres:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: example 
  #   volumes:
  #     - postgres-db:/var/lib/postgresql/data      
 

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example 
    volumes:
      - mongo-db:/data/db
         
  # mongo-express:
  
  #   image:  mongo-express:latest
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  #     ME_CONFIG_BASICAUTH_ENABLED: true
  #     ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
  #     ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
  #   depends_on:
  #     - mongo

  redis:
    image: redis:latest
    container_name: redis-cont    
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app   
volumes:
  mongo-db: 
  postgres-db: 
  